kafkaInstance:
  name: cluster-kafka
  app: kafka
  replicas: 3
  image:
    repository: confluentinc/cp-kafka
    tag: latest
  config:
    broker.id: 0
    listeners: PLAINTEXT://kafka:9092
    log.dirs: /var/lib/kafka/data
    zookeeper.connect: zookeeper:2181
    auto.create.topics.enable: 'true'
  persistence:
    enabled: true
    size: 10Gi
    storageClassName: standard
  service:
    type: ClusterIP
    port: 9092
  resources:
    limits:
      memory: 8Gi
    requests:
      memory: 4Gi    