apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaConnector
metadata:
  labels:
    strimzi.io/cluster: debezium23-ora19c-sso-connect-cluster
  name: {{ .Values.KafkaConnectorInstance.name }}
spec:
  class: io.debezium.connector.oracle.OracleConnector
  config:
    table.include.list: >-
      {{ .Values.KafkaConnectorInstance.config.table.include.list | indent 6 }}
    tasks.max: 1
    database.hostname: {{ .Values.kafkaconnector.connector.database.hostname }}
    snapshot.mode: initial
    database.password: '${secrets:kafka/debezium-secret:password}'
    topic.prefix: ora_hmg.hmg
    schema.include.list: 'CA,FI'
    database.connection.adapter: logminer
    database.port: 1521
    connector.class: io.debezium.connector.oracle.OracleConnector
    log.mining.transaction.retention.hours: 4
    database.dbname: HMG
    schema.history.internal.kafka.topic: hmg-ca-tables-history
    database.user: '${secrets:kafka/debezium-secret:username}'
    schema.history.internal.kafka.bootstrap.servers: {{ .Values.KafkaConnectorInstance.config.schema.history.internal.kafka.bootstrap.servers }}
    snapshot.include.collection.list: >-
      {{ .Values.KafkaConnectorInstance.config.table.include.list | indent 6 }}
    log.mining.batch.size.max: 50000000
  tasksMax: 1