apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  labels:
    app: kafka
  name: cluster-kafka
  namespace: kafka
spec:
  entityOperator:
    topicOperator: {}
    userOperator: {}
  kafka:
    config:
      default.replication.factor: 3
      inter.broker.protocol.version: '3.4'
      min.insync.replicas: 2
      offsets.topic.replication.factor: 3
      transaction.state.log.min.isr: 2
      transaction.state.log.replication.factor: 3
    resources:
      limits:
        memory: 8Gi
      requests:
        memory: 4Gi
    readinessProbe:
      failureThreshold: 3
      initialDelaySeconds: 15
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 6
    livenessProbe:
      failureThreshold: 3
      initialDelaySeconds: 15
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 6
    version: 3.4.0
    storage:
      class: nfs-client
      size: 200Gi
      type: persistent-claim
    replicas: 3
    jvmOptions:
      '-Xms': 6g
      '-Xmx': 6g
    listeners:
      - name: plain
        port: 9092
        tls: false
        type: internal
      - name: tls
        port: 9093
        tls: true
        type: internal
      - configuration:
          bootstrap:
            host: cluster-kafka-kafka-bootstrap-kafka.hmg.unifor.br
          brokerCertChainAndKey:
            certificate: wildcard-hmg-unifor.br-2025.crt
            key: wildcard-hmg-unifor.br-2025.key
            secretName: wildcard-unifor-certificate2025
        name: external
        port: 9094
        tls: true
        type: route
    logging:
      loggers:
        kafka.root.logger.level: INFO
      type: inline
  zookeeper:
    jvmOptions:
      '-Xms': 4g
      '-Xmx': 4g
    livenessProbe:
      failureThreshold: 3
      initialDelaySeconds: 15
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 6
    logging:
      loggers:
        zookeeper.root.logger: INFO
      type: inline
    readinessProbe:
      failureThreshold: 3
      initialDelaySeconds: 15
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 6
    replicas: 3
    resources:
      limits:
        memory: 5Gi
      requests:
        memory: 2Gi
    storage:
      class: nfs-client
      size: 100Gi
      type: persistent-claim